# Generated by Django 4.2.6 on 2024-01-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sleep_date', models.DateTimeField()),
                ('end_sleep_date', models.DateTimeField()),
                ('sleep_duration', models.FloatField()),
            ],
        ),
    ]
